name: hearthstone_info
description: A Dart program that asynchronously fetches information from the Hearthstone API, processes the response, and displays relevant information to the user.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
